### ISSUE TITLE
[QHA] Calculate all properties

### ISSUE THREAD

**Issue by jan-janssen** [pyiron/atomistics#130]
Currently, the quasi-harmonic approximation is only applied to calculate the volume expansion, still it would be great to extend this to all thermodynamic properties. In addition, just like it is done for LAMMPS, it would be great to return the properties as a dictionary and give the user the choice to select which properties to return.

**Comment by samwaseda** [comment]
It's related to [my previous PR](https://github.com/pyiron/atomistics/issues/112). I'll take a look over Christmas
