### ISSUE TITLE
[critical][performance][architecture]: Avoid double loops

### ISSUE THREAD

**Issue by liamhuber** [pyiron/atomistics#27]
The current evaluators for both [lammps](https://github.com/pyiron/atomistics/blob/8a6ad7fa5700b46d3f6e494050f37e9c844e697e/atomistics/calculators/lammps_library/calculator.py#L77) and [ASE](https://github.com/pyiron/atomistics/blob/8a6ad7fa5700b46d3f6e494050f37e9c844e697e/atomistics/calculators/ase_interface/calculator.py#L11) calculators loop over the `calc_energy` flag and `calc_forces` flag separately. As far as I can tell, that means if I ask for both forces _and_ energies for the same set of structures, I do 2x as many calculations as I need.

My gut-response is to restructure the task list so that each structure appears once, and then empower the calculators to handle different properties (_always_ forces and energies, but optionally other things). I'm sure there are other solutions too though.

**Comment by pmrv** [comment]
In practice I think this doesn't end up costing us, because ASE calculators cache these things if the structure doesn't change, but the proposed restructuring of the results dict is imo clearer and helpful for non-ASE things.

**Comment by pmrv** [comment]
> In practice I think this doesn't end up costing us, because ASE calculators cache these things if the structure doesn't change, but the proposed restructuring of the results dict is imo clearer and helpful for non-ASE things.

Ah, disregard.  I thought again and it's like you said, by changing the structure in between the cache is invalidated.
