### ISSUE TITLE
[nit] There's a test for that: AlmostEqual

### ISSUE THREAD

**Issue by liamhuber** [pyiron/atomistics#28]
[Here](https://github.com/pyiron/atomistics/blob/8a6ad7fa5700b46d3f6e494050f37e9c844e697e/tests/test_elastic_gpaw.py#L38) and elsewhere, the pattern `self.assertTrue(np.isclose(SOME_FLOAT, 3.14159265359))` can be replaced with the simpler `self.assertAlmostEqual(SOME_FLOAT, 3.14159265359)`. This makes the intent easier to see and avoids the numpy import (at least in the linked reference, `np` is only used to access `isclose`.)

**Comment by jan-janssen** [comment]
This was implemented in https://github.com/pyiron/atomistics/pull/251
