### ISSUE TITLE
Where are the potential files stored?

### ISSUE THREAD

**Issue by samwaseda** [pyiron/atomistics#319]
I tried the code snippet from [this page](https://atomistics.readthedocs.io/en/latest/simulation_codes.html#lammps) but `atomistics` couldn't locate the potential files. Where am I supposed to get them from? I have a cloned version of atomistics and for the Lammps installation I followed the steps given [here](https://atomistics.readthedocs.io/en/latest/simulation_codes.html#lammps)

**Comment by jan-janssen** [comment]
Good catch, you can install them using: 
```
conda install -c conda-forge iprpy-data 
```

**Comment by samwaseda** [comment]
Hm it's actually already installed (sorry I pasted a wrong link above but `iprpy-data` is already included in the [installation guide](https://atomistics.readthedocs.io/en/latest/installation.html#conda-based-installation))

**Comment by samwaseda** [comment]
I reformulate: I have it already but still `atomistics` doesn’t find potential files

**Comment by jan-janssen** [comment]
Can you check the following two environment variables? `CONDA_PREFIX`, `CONDA_DIR` are those set? 
```
import os
print(os.environ["CONDA_PREFIX"])
```
If they are not set then you can always call the `get_potential_by_name()` function with the full path to your potentials:
```
from atomistics.calculators import get_potential_by_name

get_potential_by_name(
        potential_name="1999--Mishin-Y--Al--LAMMPS--ipr1",
        resource_path=os.path.join(os.environ["CONDA_PREFIX"], "share", "iprpy"),
)
```
