### ISSUE TITLE
`format_black` label fails on PR from fork

### ISSUE THREAD

**Issue by liamhuber** [pyiron/atomistics#35]
Automatic black formatting via label failed over on #33. The error occurred at `actions/checkout@v3`:

```
Run actions/checkout@v3
  with:
    ref: abstract_calculator
    fetch-depth: 0
    repository: pyiron/atomistics
    ssh-strict: true
    persist-credentials: true
    clean: true
    sparse-checkout-cone-mode: true
    fetch-tags: false
    lfs: false
    submodules: false
    set-safe-directory: true
Error: Input required and not supplied: token
```

However the action uses the `DEPENDABOT_WORKFLOW_TOKEN`, which I can indeed see has been set in the secrets.
```
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.DEPENDABOT_WORKFLOW_TOKEN }}
```

My suspicion is that this is an artefact of the PR being from my fork where the token is not set.

If this understanding is correct, then for me this would be an argument against requiring in-team devs to make all their PRs by fork.

When I tried to push the branch containing the centralized workflow from PyCharm I web-authenticated and got an OK message, but the push still failed, which surprised me since a team I'm on has admin rights to this repo. @jan-janssen what is the intended behaviour for this repo? I looked in the settings and didn't see anything to (dis)allow direct pushes from members, so I'm not totally clear if I was actually trying to do something that's been forbidden or if PyCharm and GitHub are just borking my identification process.

**Comment by jan-janssen** [comment]
> @jan-janssen what is the intended behaviour for this repo? 

I tried to configure the repository just like all the other pyiron repositories. This was not done in the beginning but since yesterday everything should be just like all the other repositories https://github.com/pyiron/atomistics/pull/33#issuecomment-1714971330

**Comment by liamhuber** [comment]
> > @jan-janssen what is the intended behaviour for this repo?
> 
> I tried to configure the repository just like all the other pyiron repositories. This was not done in the beginning but since yesterday everything should be just like all the other repositories [#33 (comment)](https://github.com/pyiron/atomistics/pull/33#issuecomment-1714971330)

Ok, then the black labeling is (hopefully) just because that PR is coming from a fork.

The inability to push directly to the repo is probably a PyCharm-GitHub problem on my end and I'll try again later.
