### ISSUE TITLE
Avoid mutable defaults

### ISSUE THREAD

**Issue by liamhuber** [pyiron/atomistics#62]
Is it really intentional that the `axes` default [is a mutable list](https://github.com/pyiron/atomistics/blob/26c0531fd7be8f7455beb2b9f2c452ed9f7d0b6f/atomistics/workflows/evcurve/workflow.py#L78)? This can cause we're edge-case behaviour:

```python
from ase.build import bulk
from atomistics.workflows.evcurve.workflow import EnergyVolumeCurveWorkflow

ev1 = EnergyVolumeCurveWorkflow(bulk("Al"))
ev2 = EnergyVolumeCurveWorkflow(bulk("Cu"))
print(ev2.axes)
>>> ['x', 'y', 'z']
ev1.axes.pop()
print(ev2.axes)
>>> ['x', 'y']
```

**Comment by jan-janssen** [comment]
Would you suggest to use a tuple instead? `('x', 'y', 'z')`

**Comment by liamhuber** [comment]
I think that should work, although it might involve also changing type hints (including downstream). The other alternative is to set it to None and if None set to list in init. The tuple sounds better to me in this case.

**Comment by samwaseda** [comment]
I'm not really sure whether I understand the urgency. Is it something that could realistically occur and we should be worried about, or is it just something we could think of when list of tuple doesn't make a functional difference?

**Comment by liamhuber** [comment]
I mean, it's a bug; modifying the axes of one instance should not have any impact on the other. Urgent? I guess not, but it should still be fixed. For me, the sense of urgency comes because mutable defaults are a dangerous habit, and these same defaults are now duplicated in the PR to "nodize" these functions, so the infection is spreading. I'd rather cure it as early as possible.
