### ISSUE TITLE
[documentation] The name `calculator` for the workflows is confusing

### ISSUE THREAD

**Issue by jan-janssen** [pyiron/atomistics#9]
A calculator is typically associated with a simulator to evaluate atomistic structures and then return energies and forces. So it would be great to rename the workflows to something other than `calculator`.

**Comment by niklassiemer** [comment]
Just stating a few ideas from the chat:
Calculator, Interpreter, Engine, PropertyEvaluator, AtomisticInterpreter

**Comment by jan-janssen** [comment]
In https://github.com/pyiron/atomistics/pull/19 I renamed the `Calculators` to `Workflows` and introduced `Calculators` as the name for the codes which evaluate the structures and return energies or forces.
